library(dplyr)
library(openxlsx)

C5_methodology_2018 <- read.xlsx(paste0(data_dir, "input/CDP_2018_Global_aggregation_raw_response.xlsx"), sheet = "C5 - Emissions methodology")
names(C5_methodology_2018) <- str_replace_all(names(C5_methodology_2018), "\\.", " ")
write.xlsx(C5_methodology_2018, paste0(data_dir, "output/C5_EmissionsMethodology_", 2018, ".xlsx"), sheetName = "C5 - Emissions methodology")
C5_methodology_2019 <- read.xlsx(paste0(data_dir, "input/CDP_2019_Global_aggregation_raw_response.xlsx"), sheet = "C5 - Emissions methodology")
names(C5_methodology_2019) <- str_replace_all(names(C5_methodology_2019), "\\.", " ")
write.xlsx(C5_methodology_2019, paste0(data_dir, "output/C5_EmissionsMethodology_", 2019, ".xlsx"), sheetName = "C5 - Emissions methodology")
C5_methodology_2020 <- read.xlsx(paste0(data_dir, "input/CDP_2020_Global_aggregation_raw_response.xlsx"), sheet = "C5 - Emissions methodology")
names(C5_methodology_2020) <- str_replace_all(names(C5_methodology_2020), "\\.", " ")
write.xlsx(C5_methodology_2020, paste0(data_dir, "output/C5_EmissionsMethodology_", 2020, ".xlsx"), sheetName = "C5 - Emissions methodology")
C5_methodology_2021 <- read.xlsx(paste0(data_dir, "input/CDP_2021_Global_aggregation_raw_response.xlsx"), sheet = "C5 - Emissions methodology")
names(C5_methodology_2021) <- str_replace_all(names(C5_methodology_2021), "\\.", " ")
write.xlsx(C5_methodology_2021, paste0(data_dir, "output/C5_EmissionsMethodology_", 2021, ".xlsx"), sheetName = "C5 - Emissions methodology")
C5_methodology_2022 <- read.xlsx(paste0(data_dir, "input/2023_NSA_report_CDP_2022_climate_raw_response.xlsx"), sheet = "C5.3")
names(C5_methodology_2022) <- str_replace_all(names(C5_methodology_2022), "\\.", " ")
write.xlsx(C5_methodology_2022, paste0(data_dir, "output/C5_EmissionsMethodology_", 2022, ".xlsx"), sheetName = "C5 - Emissions methodology")
